// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package email

import (
	"fmt"
	"strings"
)

const (
	// EmailTypeVerification is a EmailType of type Verification.
	EmailTypeVerification EmailType = iota
	// EmailTypePasswordReset is a EmailType of type Password_reset.
	EmailTypePasswordReset
	// EmailTypeNotification is a EmailType of type Notification.
	EmailTypeNotification
)

var ErrInvalidEmailType = fmt.Errorf("not a valid EmailType, try [%s]", strings.Join(_EmailTypeNames, ", "))

const _EmailTypeName = "verificationpassword_resetnotification"

var _EmailTypeNames = []string{
	_EmailTypeName[0:12],
	_EmailTypeName[12:26],
	_EmailTypeName[26:38],
}

// EmailTypeNames returns a list of possible string values of EmailType.
func EmailTypeNames() []string {
	tmp := make([]string, len(_EmailTypeNames))
	copy(tmp, _EmailTypeNames)
	return tmp
}

// EmailTypeValues returns a list of the values for EmailType
func EmailTypeValues() []EmailType {
	return []EmailType{
		EmailTypeVerification,
		EmailTypePasswordReset,
		EmailTypeNotification,
	}
}

var _EmailTypeMap = map[EmailType]string{
	EmailTypeVerification:  _EmailTypeName[0:12],
	EmailTypePasswordReset: _EmailTypeName[12:26],
	EmailTypeNotification:  _EmailTypeName[26:38],
}

// String implements the Stringer interface.
func (x EmailType) String() string {
	if str, ok := _EmailTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("EmailType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EmailType) IsValid() bool {
	_, ok := _EmailTypeMap[x]
	return ok
}

var _EmailTypeValue = map[string]EmailType{
	_EmailTypeName[0:12]:                   EmailTypeVerification,
	strings.ToLower(_EmailTypeName[0:12]):  EmailTypeVerification,
	_EmailTypeName[12:26]:                  EmailTypePasswordReset,
	strings.ToLower(_EmailTypeName[12:26]): EmailTypePasswordReset,
	_EmailTypeName[26:38]:                  EmailTypeNotification,
	strings.ToLower(_EmailTypeName[26:38]): EmailTypeNotification,
}

// ParseEmailType attempts to convert a string to a EmailType.
func ParseEmailType(name string) (EmailType, error) {
	if x, ok := _EmailTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _EmailTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return EmailType(0), fmt.Errorf("%s is %w", name, ErrInvalidEmailType)
}

// MarshalText implements the text marshaller method.
func (x EmailType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *EmailType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseEmailType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *EmailType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

// Set implements the Golang flag.Value interface func.
func (x *EmailType) Set(val string) error {
	v, err := ParseEmailType(val)
	*x = v
	return err
}

// Get implements the Golang flag.Getter interface func.
func (x *EmailType) Get() interface{} {
	return *x
}

// Type implements the github.com/spf13/pFlag Value interface.
func (x *EmailType) Type() string {
	return "EmailType"
}
