// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package submission

import (
	"database/sql/driver"
	"errors"
	"fmt"
)

const (
	// ExecutionStatusSuccess is a ExecutionStatus of type Success.
	ExecutionStatusSuccess ExecutionStatus = iota
	// ExecutionStatusFailed is a ExecutionStatus of type Failed.
	ExecutionStatusFailed
	// ExecutionStatusError is a ExecutionStatus of type Error.
	ExecutionStatusError
)

var ErrInvalidExecutionStatus = errors.New("not a valid ExecutionStatus")

const _ExecutionStatusName = "successfailederror"

var _ExecutionStatusMap = map[ExecutionStatus]string{
	ExecutionStatusSuccess: _ExecutionStatusName[0:7],
	ExecutionStatusFailed:  _ExecutionStatusName[7:13],
	ExecutionStatusError:   _ExecutionStatusName[13:18],
}

// String implements the Stringer interface.
func (x ExecutionStatus) String() string {
	if str, ok := _ExecutionStatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ExecutionStatus(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ExecutionStatus) IsValid() bool {
	_, ok := _ExecutionStatusMap[x]
	return ok
}

var _ExecutionStatusValue = map[string]ExecutionStatus{
	_ExecutionStatusName[0:7]:   ExecutionStatusSuccess,
	_ExecutionStatusName[7:13]:  ExecutionStatusFailed,
	_ExecutionStatusName[13:18]: ExecutionStatusError,
}

// ParseExecutionStatus attempts to convert a string to a ExecutionStatus.
func ParseExecutionStatus(name string) (ExecutionStatus, error) {
	if x, ok := _ExecutionStatusValue[name]; ok {
		return x, nil
	}
	return ExecutionStatus(0), fmt.Errorf("%s is %w", name, ErrInvalidExecutionStatus)
}

var errExecutionStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *ExecutionStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = ExecutionStatus(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = ExecutionStatus(v)
	case string:
		*x, err = ParseExecutionStatus(v)
	case []byte:
		*x, err = ParseExecutionStatus(string(v))
	case ExecutionStatus:
		*x = v
	case int:
		*x = ExecutionStatus(v)
	case *ExecutionStatus:
		if v == nil {
			return errExecutionStatusNilPtr
		}
		*x = *v
	case uint:
		*x = ExecutionStatus(v)
	case uint64:
		*x = ExecutionStatus(v)
	case *int:
		if v == nil {
			return errExecutionStatusNilPtr
		}
		*x = ExecutionStatus(*v)
	case *int64:
		if v == nil {
			return errExecutionStatusNilPtr
		}
		*x = ExecutionStatus(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = ExecutionStatus(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errExecutionStatusNilPtr
		}
		*x = ExecutionStatus(*v)
	case *uint:
		if v == nil {
			return errExecutionStatusNilPtr
		}
		*x = ExecutionStatus(*v)
	case *uint64:
		if v == nil {
			return errExecutionStatusNilPtr
		}
		*x = ExecutionStatus(*v)
	case *string:
		if v == nil {
			return errExecutionStatusNilPtr
		}
		*x, err = ParseExecutionStatus(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x ExecutionStatus) Value() (driver.Value, error) {
	return x.String(), nil
}

const (
	// SubmissionStatusPending is a SubmissionStatus of type Pending.
	SubmissionStatusPending SubmissionStatus = iota
	// SubmissionStatusRunning is a SubmissionStatus of type Running.
	SubmissionStatusRunning
	// SubmissionStatusCompleted is a SubmissionStatus of type Completed.
	SubmissionStatusCompleted
)

var ErrInvalidSubmissionStatus = errors.New("not a valid SubmissionStatus")

const _SubmissionStatusName = "pendingrunningcompleted"

var _SubmissionStatusMap = map[SubmissionStatus]string{
	SubmissionStatusPending:   _SubmissionStatusName[0:7],
	SubmissionStatusRunning:   _SubmissionStatusName[7:14],
	SubmissionStatusCompleted: _SubmissionStatusName[14:23],
}

// String implements the Stringer interface.
func (x SubmissionStatus) String() string {
	if str, ok := _SubmissionStatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("SubmissionStatus(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SubmissionStatus) IsValid() bool {
	_, ok := _SubmissionStatusMap[x]
	return ok
}

var _SubmissionStatusValue = map[string]SubmissionStatus{
	_SubmissionStatusName[0:7]:   SubmissionStatusPending,
	_SubmissionStatusName[7:14]:  SubmissionStatusRunning,
	_SubmissionStatusName[14:23]: SubmissionStatusCompleted,
}

// ParseSubmissionStatus attempts to convert a string to a SubmissionStatus.
func ParseSubmissionStatus(name string) (SubmissionStatus, error) {
	if x, ok := _SubmissionStatusValue[name]; ok {
		return x, nil
	}
	return SubmissionStatus(0), fmt.Errorf("%s is %w", name, ErrInvalidSubmissionStatus)
}

var errSubmissionStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *SubmissionStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = SubmissionStatus(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = SubmissionStatus(v)
	case string:
		*x, err = ParseSubmissionStatus(v)
	case []byte:
		*x, err = ParseSubmissionStatus(string(v))
	case SubmissionStatus:
		*x = v
	case int:
		*x = SubmissionStatus(v)
	case *SubmissionStatus:
		if v == nil {
			return errSubmissionStatusNilPtr
		}
		*x = *v
	case uint:
		*x = SubmissionStatus(v)
	case uint64:
		*x = SubmissionStatus(v)
	case *int:
		if v == nil {
			return errSubmissionStatusNilPtr
		}
		*x = SubmissionStatus(*v)
	case *int64:
		if v == nil {
			return errSubmissionStatusNilPtr
		}
		*x = SubmissionStatus(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = SubmissionStatus(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errSubmissionStatusNilPtr
		}
		*x = SubmissionStatus(*v)
	case *uint:
		if v == nil {
			return errSubmissionStatusNilPtr
		}
		*x = SubmissionStatus(*v)
	case *uint64:
		if v == nil {
			return errSubmissionStatusNilPtr
		}
		*x = SubmissionStatus(*v)
	case *string:
		if v == nil {
			return errSubmissionStatusNilPtr
		}
		*x, err = ParseSubmissionStatus(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x SubmissionStatus) Value() (driver.Value, error) {
	return x.String(), nil
}
