// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package exercise

import (
	"database/sql/driver"
	"errors"
	"fmt"
)

const (
	// DifficultyEasy is a Difficulty of type Easy.
	DifficultyEasy Difficulty = iota
	// DifficultyMedium is a Difficulty of type Medium.
	DifficultyMedium
	// DifficultyHard is a Difficulty of type Hard.
	DifficultyHard
)

var ErrInvalidDifficulty = errors.New("not a valid Difficulty")

const _DifficultyName = "easymediumhard"

var _DifficultyMap = map[Difficulty]string{
	DifficultyEasy:   _DifficultyName[0:4],
	DifficultyMedium: _DifficultyName[4:10],
	DifficultyHard:   _DifficultyName[10:14],
}

// String implements the Stringer interface.
func (x Difficulty) String() string {
	if str, ok := _DifficultyMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Difficulty(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Difficulty) IsValid() bool {
	_, ok := _DifficultyMap[x]
	return ok
}

var _DifficultyValue = map[string]Difficulty{
	_DifficultyName[0:4]:   DifficultyEasy,
	_DifficultyName[4:10]:  DifficultyMedium,
	_DifficultyName[10:14]: DifficultyHard,
}

// ParseDifficulty attempts to convert a string to a Difficulty.
func ParseDifficulty(name string) (Difficulty, error) {
	if x, ok := _DifficultyValue[name]; ok {
		return x, nil
	}
	return Difficulty(0), fmt.Errorf("%s is %w", name, ErrInvalidDifficulty)
}

var errDifficultyNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *Difficulty) Scan(value interface{}) (err error) {
	if value == nil {
		*x = Difficulty(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = Difficulty(v)
	case string:
		*x, err = ParseDifficulty(v)
	case []byte:
		*x, err = ParseDifficulty(string(v))
	case Difficulty:
		*x = v
	case int:
		*x = Difficulty(v)
	case *Difficulty:
		if v == nil {
			return errDifficultyNilPtr
		}
		*x = *v
	case uint:
		*x = Difficulty(v)
	case uint64:
		*x = Difficulty(v)
	case *int:
		if v == nil {
			return errDifficultyNilPtr
		}
		*x = Difficulty(*v)
	case *int64:
		if v == nil {
			return errDifficultyNilPtr
		}
		*x = Difficulty(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = Difficulty(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errDifficultyNilPtr
		}
		*x = Difficulty(*v)
	case *uint:
		if v == nil {
			return errDifficultyNilPtr
		}
		*x = Difficulty(*v)
	case *uint64:
		if v == nil {
			return errDifficultyNilPtr
		}
		*x = Difficulty(*v)
	case *string:
		if v == nil {
			return errDifficultyNilPtr
		}
		*x, err = ParseDifficulty(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x Difficulty) Value() (driver.Value, error) {
	return x.String(), nil
}

const (
	// ExerciseTypeFindBug is a ExerciseType of type Find_bug.
	ExerciseTypeFindBug ExerciseType = iota
	// ExerciseTypeImplementFunction is a ExerciseType of type Implement_function.
	ExerciseTypeImplementFunction
	// ExerciseTypeCompleteCode is a ExerciseType of type Complete_code.
	ExerciseTypeCompleteCode
)

var ErrInvalidExerciseType = errors.New("not a valid ExerciseType")

const _ExerciseTypeName = "find_bugimplement_functioncomplete_code"

var _ExerciseTypeMap = map[ExerciseType]string{
	ExerciseTypeFindBug:           _ExerciseTypeName[0:8],
	ExerciseTypeImplementFunction: _ExerciseTypeName[8:26],
	ExerciseTypeCompleteCode:      _ExerciseTypeName[26:39],
}

// String implements the Stringer interface.
func (x ExerciseType) String() string {
	if str, ok := _ExerciseTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ExerciseType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ExerciseType) IsValid() bool {
	_, ok := _ExerciseTypeMap[x]
	return ok
}

var _ExerciseTypeValue = map[string]ExerciseType{
	_ExerciseTypeName[0:8]:   ExerciseTypeFindBug,
	_ExerciseTypeName[8:26]:  ExerciseTypeImplementFunction,
	_ExerciseTypeName[26:39]: ExerciseTypeCompleteCode,
}

// ParseExerciseType attempts to convert a string to a ExerciseType.
func ParseExerciseType(name string) (ExerciseType, error) {
	if x, ok := _ExerciseTypeValue[name]; ok {
		return x, nil
	}
	return ExerciseType(0), fmt.Errorf("%s is %w", name, ErrInvalidExerciseType)
}

var errExerciseTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *ExerciseType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = ExerciseType(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = ExerciseType(v)
	case string:
		*x, err = ParseExerciseType(v)
	case []byte:
		*x, err = ParseExerciseType(string(v))
	case ExerciseType:
		*x = v
	case int:
		*x = ExerciseType(v)
	case *ExerciseType:
		if v == nil {
			return errExerciseTypeNilPtr
		}
		*x = *v
	case uint:
		*x = ExerciseType(v)
	case uint64:
		*x = ExerciseType(v)
	case *int:
		if v == nil {
			return errExerciseTypeNilPtr
		}
		*x = ExerciseType(*v)
	case *int64:
		if v == nil {
			return errExerciseTypeNilPtr
		}
		*x = ExerciseType(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = ExerciseType(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errExerciseTypeNilPtr
		}
		*x = ExerciseType(*v)
	case *uint:
		if v == nil {
			return errExerciseTypeNilPtr
		}
		*x = ExerciseType(*v)
	case *uint64:
		if v == nil {
			return errExerciseTypeNilPtr
		}
		*x = ExerciseType(*v)
	case *string:
		if v == nil {
			return errExerciseTypeNilPtr
		}
		*x, err = ParseExerciseType(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x ExerciseType) Value() (driver.Value, error) {
	return x.String(), nil
}
